<?php

namespace TSP\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccordRepository extends EntityRepository
{
}
