<?php

namespace TSP\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScolariteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScolariteRepository extends EntityRepository
{
}
